# Generated by Django 6.0 on 2025-12-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size_in_acres', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmcore.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('season_name', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmcore.farm')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('season_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmcore.seasonplan')),
            ],
        ),
        migrations.CreateModel(
            name='ActualActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('land_preparation', 'Land Preparation'), ('planting', 'Planting'), ('weeding', 'Weeding'), ('spraying', 'Spraying'), ('harvesting', 'Harvesting')], max_length=50)),
                ('actual_date', models.DateField()),
                ('actual_cost_ugx', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('planned_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_activities', to='farmcore.plannedactivity')),
                ('season_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_activities', to='farmcore.seasonplan')),
            ],
        ),
    ]
