# Generated by Django 5.2.7 on 2025-12-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcore', '0002_rename_phone_number_farmer_phone_farm_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
