# Generated by Django 5.2.7 on 2025-12-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcore', '0003_seasonplan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonplan',
            name='season_name',
            field=models.CharField(choices=[('season_a', 'Season A (March - July) - Long Rains'), ('season_b', 'Season B (August - November) - Short Rains'), ('season_c', 'Season C (December - February) - Dry Season')], max_length=100),
        ),
    ]
