# Generated by Django 5.2.7 on 2025-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcore', '0004_alter_seasonplan_season_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedactivity',
            name='activity_type',
            field=models.CharField(choices=[('land_preparation', 'Land Preparation'), ('planting', 'Planting'), ('weeding', 'Weeding'), ('spraying', 'Spraying'), ('harvesting', 'Harvesting')], max_length=100),
        ),
    ]
