# Generated by Django 5.2.7 on 2025-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcore', '0005_alter_plannedactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
    ]
