# Generated by Django 5.2.7 on 2025-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcore', '0006_seasonplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonplan',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='seasonplan',
            name='status',
            field=models.CharField(choices=[('is_active', 'Is Active'), ('completed', 'Completed'), ('planned', 'Planned')], default='planned', max_length=20),
        ),
    ]
