# Generated by Django 5.2.7 on 2025-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcore', '0007_remove_seasonplan_is_active_alter_seasonplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedactivity',
            name='actual_cost',
        ),
        migrations.AddField(
            model_name='plannedactivity',
            name='estimated_cost_ugx',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
