# Generated by Django 6.0 on 2025-12-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcore', '0009_remove_actualactivity_planned_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualactivity',
            name='planned_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_activities', to='farmcore.plannedactivity'),
        ),
    ]
