# Generated by Django 6.0 on 2025-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcore', '0010_actualactivity_planned_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_id',
        ),
        migrations.AlterField(
            model_name='actualactivity',
            name='actual_cost_ugx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='actualactivity',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farm',
            name='size_in_acres',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='plannedactivity',
            name='estimated_cost_ugx',
            field=models.FloatField(default=0.0),
        ),
    ]
